language: android
dist: trusty

android:
  components:
  - tools
  - platform-tools
  - android-28
  - android-22
  - sys-img-armeabi-v7a-android-22

jdk:
  - oraclejdk8

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

before_script:
  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

# script for build and release via Travis to Bintray
script:
  - ./buildViaTravis.sh

# cache between builds
cache:
  directories:
  - $HOME/.gradle

env:
  global:
  - secure: "LNE6zR6CENJjKerN8TXvP/5WXlD4Cz0f/3+IariDWWMmEUdJqbBKQieK/X6QzJdpJ7+kFqalHgwDJE6B18n2jHtO58e0RiafogVRcCQM9ri98giuJPekdvmC4fMS+KYz1jt67V4CIM7BErmk3WIw4eIKuD0q9IIuhivzesHL+DuiCQCKUahORnnWqCTm20oZqOPl4OLvp/2qB8D1sfPaKJEAbJymZYFMZ4V6wIKKoj20u6dqVkly6OEQYaqi6Y61d51Os7yXQo76vAifQKiKtgB2aLz6SQ/1WtZeZUADoadYSJe/O6HCV03FFzgBaVfp+g6zyjOPw+a8dwmOiNlYFr5RVJRPSOi+yc6/Sk4TyUl3J8n2IzL8RI9SrFfPFShrOKRxfDxNazgzCot5mmavOpjLz8Zc8/kmqFQrKtvCIKSQedM7b5aaqagawHiVUdtkaRD3CUTDtIMptOiemV3YxO2hN3kKPTyqmag3af2uZJsPtBPkpIn4mbSMZZgJ82uNAz9Auj2fLwNejSUlNmdCKkcJiCu2mznKxzj6Rx+zgExU6I1BVmk0UmTd4oUGJA/vtMaYNblhGi37MqPWKR1zixdfsTyzCCrnOFZGlAWNIGLrz4wRS/9e5pyeQWv66LFRtDrSDhlZFFhTXoATY0FJf1sRbouw75XbOOfQZijUaKM="
  - secure: "Ef38eD399NaJHR2sQ2MsJgFDsI5eymJ9GUC4odAjnFN9ZkV+RKIya3BgxqWHGOPN9FpIyKfPXhq7LK6LeozXHVliy/JEdY0Oim8olIuWFcpFrr7FtP7TRsFPwYcKnzWHsjrcxuNQRN+EAlk30C9lScjMnc1j+4A7XtZkpOwORDSSLwRCGb0KMRpKMk7xDWAiIzflcy4C0LitG6/aZ2+06pAoDNZoai+vLfSQnvWjvWJw+w5yjdOuqPWlJCiIt0DFSRKiX4za9KmpLSAeR2qmkZ/9pBpZhF/ubH8nk9fo6qLikBQLaTj/jKpawv0YvYnlOcJci63ptFtoTVPtYwGupMAswoA6AgBJxnWiJI3rbAHJHYInrfAamgIOECb3J1o+z5r8ez9l9e2REyDCqFix2N3ORFuJ9oiRzMjYuBN+JkH6KoBDkZ456H/16RkgAD1gn2N5I4Qp4nI/FYS5PAVvEh3sU8Hx9qktqDnRYJ3m3qZaqm97WgJGqJnCo1vDC3/T6ZnCM1W1MoIkDNhmbgLG0DlCouE4KMCrQ8B7Gmm8YaY7R1T/XWR+MBlLynxyzI3HWOteMLqRLOpIvR+mQCxSKK52NOqBl2thRF1fJRk4wZ8QH3cYpzYETFz0bvln1iT9v3LuAuVtwWzg3oP75Ka5YzXoNHoT+Oo/qpn8paSw420="