language: android

android:
  components:
  - tools
  - platform-tools

jdk:
- oraclejdk8

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

before_install:
# Install SDK license so Android Gradle plugin can install deps.
- mkdir "$ANDROID_HOME/licenses" || true
- echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

# script for build and release via Travis to Bintray
script: ./buildViaTravis.sh

# cache between builds
cache:
  directories:
  - $HOME/.gradle
